package com.basic.template.compose.util

object TestUITag {
    const val EMAIL_TAG = "EMAIL_TAG"
    const val PASSWORD_TAG = "PASSWORD_TAG"
    const val EMAIL_FIELD_TAG = "EMAIL_FIELD_TAG"
    const val PASSWORD_FILED_TAG = "PASSWORD_FILED_TAG"
    const val CONFIRM_PASSWORD_FILED_TAG = "CONFIRM_PASSWORD_FILED_TAG"
    const val LOGIN_BUTTON_TAG = "LOGIN_BUTTON_TAG"
    const val REGISTER_BUTTON_TAG = "REGISTER_BUTTON_TAG"
    const val USER_LIST_TITLE = "USER_LIST_TITLE"
    const val PROGRESS_BAR = "PROGRESS_BAR"
    const val SPLASH_IMAGE = "SPLASH_IMAGE"
    const val ALL_READY_HAVE_ACCOUNT_TAG = "ALL_READY_HAVE_ACCOUNT_TAG"
    const val DO_NOT_HAVE_ACCOUNT_TAG = "DO_NOT_HAVE_ACCOUNT_TAG"
    const val USER_DETAIL_TAG = "USER_DETAIL_TAG"
    const val USER_EMAIL_TAG = "USER_EMAIL_TAG"
    const val USER_FIRST_NAME_TAG = "USER_FIRST_NAME_TAG"
    const val USER_LAST_NAME_TAG = "USER_LAST_NAME_TAG"
    const val NAVIGATION_DRAWER_TAG = "NAVIGATION_DRAWER_TAG"
}